version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y jq
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - PACKAGE_VERSION="$(cat package.json | jq '.version')"
      - IMAGE_URI="${REPOSITORY_URI}:${PACKAGE_VERSION}"
  build:
    commands:
      - docker build -t "$IMAGE_URI" .
  post_build:
    commands:
      - docker push "$IMAGE_URI"
