version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - PACKAGE_VERSION="$(grep version package.json | cut -c 15- | rev | cut -c 3- | rev)"
      - IMAGE_URI="${REPOSITORY_URI}:${PACKAGE_VERSION}"
  build:
    commands:
      - docker build -t "$IMAGE_URI" .
  post_build:
    commands:
      - docker push "$IMAGE_URI"
