version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - PACKAGE_VERSION="$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }') # | sed 's/[\",]//g')"
      - IMAGE_URI="${REPOSITORY_URI}:${PACKAGE_VERSION}"
  build:
    commands:
      - docker build -t "$IMAGE_URI" .
 post_build:
    commands:
      - docker push "$IMAGE_URI"
